# Generated by Django 2.2.13 on 2020-06-19 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customtext_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customtext',
            old_name='test',
            new_name='test3',
        ),
    ]
